[package]
name = "infotainer-common"
version = "0.1.0"
edition = "2021"

[lib]
name = "infotainer"
src = "src/lib.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
